# Workflow for the api of spielD

name: API CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Nodejs
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
          
      - name: Installing Dependencies
        working-directory: ./api
        run: |
          npm ci
      - name: Eslint
        working-directory: ./api
        run: |
          npm run lint
      - name: Jest
        working-directory: ./api
        run: |
          npm run test